name: 'Install sv2v'
description: 'Install sv2v SystemVerilog to Verilog converter'
runs:
  using: 'composite'
  steps:
    - name: Install sv2v
      shell: bash
      run: |
        SV2V_VERSION=0.0.13
        SV2V_ZIP_NAME=sv2v-Linux.zip
        SV2V_ZIP_URL=https://github.com/zachjs/sv2v/releases/download/v${SV2V_VERSION}/${SV2V_ZIP_NAME}
        SV2V_ZIP_HASH="552799a1d76cd177b9b4cc63a3e77823a3d2a6eb4ec006569288abeff28e1ff8 ${SV2V_ZIP_NAME}"

        mkdir /tmp/sv2v
        cd /tmp/sv2v
        wget ${SV2V_ZIP_URL}
        echo ${SV2V_ZIP_HASH} | sha256sum -c
        unzip ${SV2V_ZIP_NAME}
        chmod +x sv2v-Linux/sv2v
        sudo cp sv2v-Linux/sv2v /usr/local/bin
        rm -rf /tmp/sv2v
